# Generated by Django 5.1.2 on 2024-10-23 02:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=200, null=True)),
                ('nip', models.CharField(blank=True, max_length=200, null=True)),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presensi.kelas')),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(blank=True, max_length=200, null=True)),
                ('nama', models.CharField(blank=True, max_length=200, null=True)),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presensi.kelas')),
            ],
        ),
        migrations.CreateModel(
            name='Kehadiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('wktdatang', models.TimeField(blank=True, null=True)),
                ('wktpulang', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=99, null=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presensi.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nis', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('token', models.CharField(blank=True, max_length=99, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('guru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presensi.guru')),
                ('siswa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presensi.siswa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
