# Generated by Django 5.1.2 on 2024-10-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='jurusan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
