# Generated by Django 5.1.2 on 2024-10-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0002_kelas_jurusan'),
    ]

    operations = [
        migrations.AddField(
            model_name='kehadiran',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='kehadiran_files/'),
        ),
        migrations.AddField(
            model_name='kehadiran',
            name='keterangan',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
