# Generated by Django 5.1.2 on 2024-10-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0003_kehadiran_file_kehadiran_keterangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='kehadiran',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
