# Generated by Django 5.1.2 on 2024-10-28 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0004_kehadiran_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presensi.kelas'),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presensi.kelas'),
        ),
    ]
