# Generated by Django 5.1.2 on 2024-10-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0005_alter_guru_kelas_alter_siswa_kelas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guru',
            name='kelas',
        ),
    ]
