# Generated by Django 4.2.13 on 2024-10-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=200, null=True)),
                ('nip', models.CharField(blank=True, max_length=200, null=True)),
                ('kelas', models.CharField(blank=True, max_length=99, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kehadiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.CharField(blank=True, max_length=200, null=True)),
                ('wktdatang', models.CharField(blank=True, max_length=200, null=True)),
                ('wktpulang', models.CharField(blank=True, max_length=99, null=True)),
                ('siswa', models.CharField(blank=True, max_length=99, null=True)),
                ('status', models.CharField(blank=True, max_length=99, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(blank=True, max_length=200, null=True)),
                ('nama', models.CharField(blank=True, max_length=200, null=True)),
                ('kelas', models.CharField(blank=True, max_length=99, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('siswa', models.CharField(blank=True, max_length=200, null=True)),
                ('token', models.CharField(blank=True, max_length=99, null=True)),
                ('guru', models.CharField(blank=True, max_length=99, null=True)),
            ],
        ),
    ]
