# Generated by Django 5.1.2 on 2024-10-23 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0002_remove_user_siswa_user_groups_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kehadiran',
            name='siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presensi.siswa'),
        ),
    ]
