# Generated by Django 5.1.2 on 2024-10-23 02:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presensi', '0003_alter_kehadiran_siswa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='siswa',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='presensi.siswa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guru',
            name='kelas',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='presensi.kelas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siswa',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presensi.kelas'),
        ),
        migrations.AlterField(
            model_name='user',
            name='guru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presensi.guru'),
        ),
    ]
